import { fields as commonFields } from '@/components/Data/fields'
export const fields = {
  ...commonFields,
  ...{
    // 案件
    caseName: '案名',
    caseNumber: '字号',
    caseUseName: '案号',
    why: '案由',
    type: '类别',
    client: '委托人',
    oppositeLitigant: '对方当事人',
    litigant: '当事人',
    name: '当事人姓名或单位名称',
    idType: '当事人证件类型',
    idNumber: '当事人证件号码',
    parties: '当事人当事方',
    stage: '代理阶段',
    disputePrice: '争议标的额',
    price: '律师代理费',
    power: '代理权限',
    term: '代理期限',
    department: '受理部门',
    memo: '备注',
    contract: '合同',
    letter: '所函',
    // 发票
    inType: '发票类型',
    inNumber: '发票号码',
    inHave: '含税价',
    inTax: '税率',
    inNot: '不含税价',
    inRate: '税额',
    invoiceDate: '发票日期',
    // 进账
    enterPrice: '入账金额',
    enterDate: '入账日期',
    // 其它
    delivery: '原件',
    clientUseName: '合同客户',
    buyCompany: '购访企业',
    createRealName: '承办律师',
    createTime: '创建时间',
    caseYear: '创建年份',
    createYearMonth: '创建年月',
    payed: '现律所已支付',
    addPay: '增加律所已支付',
    membered: '现会员费个人',
    addMember: '增加会员费个人',
    nowSalary: '现有工资',
    addSalary: '增加工资',
    nowUncleared: '现有未结清',
    addUncleared: '增加未结清',
    nowTaxed: '现有增值税款',
    addTaxed: '增加增值税款'
  }
}
